#!/bin/zsh

# Improved version of the script found on http://voipbl.org/

# Create a cronjob like this:
# 0 */4 * * * /usr/local/sbin/voipbl

URL="http://www.voipbl.org/update/"
BL="/etc/fail2ban/voipbl.txt"
RP="/etc/fail2ban/repeaters.txt"
DROPBL="/etc/fail2ban/drop.txt"
DROPURL="https://www.spamhaus.org/drop/drop.txt"
EDROPBL="/etc/fail2ban/edrop.txt"
EDROPURL="https://www.spamhaus.org/drop/edrop.txt"
CHINA="/etc/fail2ban/china.txt"
JOINEDBL="/etc/fail2ban/joinedbl.txt"

# Checking for repeat offenders.
awk '/Ban/ {print $NF}' /var/log/fail2ban.log|sort|uniq -c|sort|grep -v ' [1-3] '|tail -n 10|awk '{print $2}' >> $RP
# Remove duplicates
sort $RP | uniq > ${RP}.tmp
mv ${RP}.tmp $RP

# exit on any error.
set -e

echo "Downloading rules from VoIP Blacklist"
wget -q $URL -O $BL

#echo "Downloading rules from Drop Blacklist"
wget -q $DROPURL -O $DROPBL

#echo "Downloading rules from EDrop Blacklist"
wget -q $EDROPURL -O $EDROPBL

echo "Joining all rules."
cat $RP $BL $DROPBL $EDROPBL $CHINA | sed -e 's|;.*||;s|/32||;s| *$||' | egrep -hv '(#|0\.0\.0\.0)' | grep -v '^$' | sort | uniq > $JOINEDBL

echo "Loading rules..."

# If the voipbl list does not exists, create it and fill it with $JOINEDBL
if ipset -quiet create voipbl hash:net hashsize 131072 maxelem 2600000; then
    for i in $(< $JOINEDBL); do
        /usr/sbin/ipset add voipbl $i >& /dev/null || :
    done
else # If the voipbl list already exists, remove old entries and add new ones. Usually much faster.
    CURRENT=$(mktemp)
    ipset list voipbl | grep -v ':' | sort | uniq > $CURRENT

    diff -w $CURRENT $JOINEDBL | while read io entry; do
        case $io in
            '>')
                ipset add voipbl $entry
            ;;
            '<')
                ipset del voipbl $entry
            ;;
        esac
    done

    rm $CURRENT
fi

echo "Done! Rules loaded"
